### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by milliorn** [milliorn/Netflix-Landing-Page#78]
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Footer`. See https://reactjs.org/link/warning-keys for more information.
    at li
    at Footer (http://localhost:3000/Netflix-Landing-Page/static/js/bundle.js:256:23)
    at div
    at div
    at App (http://localhost:3000/Netflix-Landing-Page/static/js/bundle.js:91:86)

```jsx
import React from "react";
import {
  footerLeft,
  footerLeftCenter,
  footerRight,
  footerRightCenter,
} from "../util/data";

export function Footer(props) {
  const listAnchor = (e, i) => (
    <li>
      <a
        className="leading-10 hover:text-gray-400"
        target="_blank"
        rel="noreferrer"
        href={e.href}
        key={i}
      >
        {e.text}
      </a>
    </li>
  );

  const dataLeftCenter = footerLeftCenter.map((e, i) => listAnchor(e, i));
  const dataRight = footerRight.map((e, i) => listAnchor(e, i));
  const dataRightCenter = footerRightCenter.map((e, i) => listAnchor(e, i));

  return (
    <footer className="mx-auto overflow-auto text-left bg-black footer ">
      <p className="mt-2 mb-6 hover:text-white text-sm sm:text-base">
        {props.footerParagraph}
      </p>
      <div className="grid gap-2 text-sm sm:grid-cols-4 grid-cols-2 mb-8 sm:mb-16">
        <ul className="list-none">
          {footerLeft.map((e, i) => listAnchor(e, i))}
        </ul>
        <ul className="list-none">{dataLeftCenter}</ul>
        <ul className="list-none">{dataRight}</ul>
        <ul className="list-none">{dataRightCenter}</ul>
      </div>
    </footer>
  );
}
```

**Comment by milliorn** [comment]
react_devtools_backend.js:3973 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `TabContentMiddle`. See https://reactjs.org/link/warning-keys for more information.
    at div
    at TabContentMiddle (http://localhost:3000/Netflix-Landing-Page/static/js/bundle.js:742:25)
    at div
    at section
    at TabContentCurrent (http://localhost:3000/Netflix-Landing-Page/static/js/bundle.js:526:23)
    at div
    at div
    at App (http://localhost:3000/Netflix-Landing-Page/static/js/bundle.js:91:86)
```jsx
import { middleTabCenter, middleTabLeft, middleTabRight } from "../util/data";

export function TabContentMiddle(props) {
  const buildTabs = (e, i) => (
    <div>
      <img className="w-full" src={e.src} alt={e.alt} />
      <p className="mx-0 my-2 mb-6 text-xl font-bold">{e.pTop}</p>
      <p className="mx-0 my-2 text-gray-400">{e.pBottom}</p>
    </div>
  );

  const tabLeft = middleTabLeft.map((e, i) => buildTabs(e, i));
  const tabMiddle = middleTabCenter.map((e, i) => buildTabs(e, i));
  const tabRight = middleTabRight.map((e, i) => buildTabs(e, i));

  return (
    <div id="tab-2-content" className="text-center">
      <div className="sm:flex-grid sm:items-start gap-4 tab-2-content-top sm:flex justify-center">
        <p className="mx-0 my-2 mb-4 sm:text-2xl text-xl leading-none">
          {props.p}
        </p>
        <a
          href={props.href}
          rel={props.rel}
          target={props.target}
          className="items-center inline-block px-5 py-3 mr-2 text-sm lg:text-base text-center text-white uppercase border-none cursor-pointer btn rounded-none  btn-lg hover:opacity-90"
        >
          <span>{props.anchorText}</span>
        </a>
      </div>
      <div className="gap-8 mt-8 text-center grid-cols-3 sm:flex w-9/12 mx-auto items-baseline ">
        {tabLeft} {tabMiddle} {tabRight}
      </div>
    </div>
  );
}
```

**Comment by milliorn** [comment]
react_devtools_backend.js:3973 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `TabContentRight`. See https://reactjs.org/link/warning-keys for more information.
    at tr
    at TabContentRight (http://localhost:3000/Netflix-Landing-Page/static/js/bundle.js:894:25)
    at div
    at section
    at TabContentCurrent (http://localhost:3000/Netflix-Landing-Page/static/js/bundle.js:526:23)
    at div
    at div
    at App (http://localhost:3000/Netflix-Landing-Page/static/js/bundle.js:91:86)
```jsx
import {
  tableRowEight,
  tableRowSeven,
  tableRowSix,
  tableRowFive,
  tableRowFour,
  tableRowThree,
  tableRowTwo,
  tableRowOne,
} from "../util/data";

export function TabContentRight(props) {
  const tdClassName = "px-5 py-3 text-center text-gray-400";

  const buildTableData = (e, i) => (
    <tr>
      <td className={tdClassName}>{e.span1}</td>
      <td className={tdClassName}>{e.span2}</td>
      <td className={tdClassName}>{e.span3}</td>
      <td className={tdClassName}>{e.span4}</td>
    </tr>
  );

  const tableOne = tableRowOne.map((e, i) => buildTableData(e, i));
  const tableTwo = tableRowTwo.map((e, i) => buildTableData(e, i));
  const tableThree = tableRowThree.map((e, i) => buildTableData(e, i));
  const tableFour = tableRowFour.map((e, i) => buildTableData(e, i));
  const tableFive = tableRowFive.map((e, i) => buildTableData(e, i));
  const tableSix = tableRowSix.map((e, i) => buildTableData(e, i));
  const tableSeven = tableRowSeven.map((e, i) => buildTableData(e, i));
  const tableEight = tableRowEight.map((e, i) => buildTableData(e, i));

  return (
    <div id="tab-3-content" className="overflow-visible overflow-x-auto ">
      <div className="text-center">
        <p className="mx-auto my-2 mb-4 sm:text-2xl text-xl w-10/12">
          {props.p}
        </p>
        <a
          href={props.href}
          rel={props.rel}
          target={props.target}
          className="items-center inline-block px-5 py-2 mr-2 text-sm lg:text-base text-white uppercase border-none cursor-pointer btn rounded-none  btn-lg hover:opacity-90"
        >
          <span>{props.span}</span>
        </a>
      </div>

      <table className="table w-10/12 mt-8 mx-auto">
        <thead>
          <tr className="uppercase">
            <th className="p-3.5"></th>
            <th className="p-3.5">{props.th1}</th>
            <th className="p-3.5">{props.th2}</th>
            <th className="p-3.5">{props.th3}</th>
          </tr>
        </thead>

        <tbody className="align-middle border-inherit">
          {tableOne}
          {tableTwo}
          {tableThree}
          {tableFour}
          {tableFive}
          {tableSix}
          {tableSeven}
          {tableEight}
        </tbody>
      </table>
    </div>
  );
}
```
